version: "2.2"

services:
  automlbench:
    image: automl:1.0.0
    build:
      context: .
    container_name: automlbench
    ports:
      - "9090:8888"
    volumes:
      - "$PWD:/opt/notebooks:Z"
    stdin_open: true
    privileged: true
    network_mode: "host"
    networks:
      - overlay
    tty: true
    security_opt:
      - no-new-privileges

networks:
  overlay:

